name: TICS image CI

on:
   push:
     tags:
       - '*.*.*'

jobs:
   build_and_publish: 
      runs-on: ubuntu-latest
      steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKGTOKEN }}
          
      - name: Extract tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push the app image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/canonical/ticsimg:${{ env.TAG }}
          push: true
          secrets: |
                    "env=${{ secrets.TICSAUTHTOKEN }}"
