name: Test tics_installer.sh

on:
   push

jobs:
   build_and_publish: 
      runs-on: ubuntu-latest
      steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Execute the tics_installer.sh script
        run: |
             chmod +x tics_installer.sh
             ./tics_installer.sh
