name: TICS run self-hosted test (script)

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: stg-tiobe
            
    steps:
    - name: Checkout the project
      uses: actions/checkout@v4

    - name: Run TICS analysis with a script
      run: |
           set -x
           export TICSAUTHTOKEN="${{ secrets.TICSAUTHTOKEN }}"
           cd test/
           which TICSQServer
           source /home/ubuntu/.profile
           which TICSQServer
           TICSQServer -project testimage -tmpdir /tmp/tics -branchdir .
