name: TICS run self-hosted test (script)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
            
    steps:
    - name: Checkout the project
      uses: actions/checkout@v4

    - name: Run TICS analysis with a script
      run: |
           export TICSAUTHTOKEN="${{ secrets.TICSAUTHTOKEN }}"
           cd test/
           source ~/.profile
           TICSQServer -project testimage -tmpdir /tmp/tics -branchdir .
