name: TICS run self-hosted test (github-action)

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:

    runs-on: [self-hosted, amd64, tiobe, noble]
      
    steps:
    
    - name: Checkout the project
      uses: actions/checkout@v4

    - name: Run TICS analysis with github-action
      uses: tiobe/tics-github-action@v3
      with:
        mode: qserver
        project: testimage
        branchdir: .
        viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
        ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
        installTics: true
